export const user = {
  plan: 'basic',
  name: 'John Doe',
  email: 'johndoe@gmail.com',
  country: 'United States',
  position: 'Designer',
  history: [
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'arrow-chevron-down.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.svg',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'aquarium.png',
    },
    {
      date: new Date(),
      item: 'arrow-circle-left.svg',
    },
  ],
  invoices: [
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: true,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 19.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'monthly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Advance',
      planDuration: 'monthly',
      amount: 29.5,
      status: 'Paid',
      refunded: false,
    },
    {
      date: new Date(),
      plan: 'Pro',
      planDuration: 'yearly',
      amount: 9.5,
      status: 'Paid',
      refunded: false,
    },
  ]
}

export const items = [
  {
    name: 'aquarium.svg',
    subscription: 'advance',
    royaltyFree: 'Yes'
  },
  {
    name: 'aquarium.png',
    subscription: 'basic',
    royaltyFree: 'Public Domain'
  },
  {
    name: 'arrow-circle-left.svg',
    subscription: 'pro',
    royaltyFree: 'None, must attribute'
  },
  {
    name: 'arrow-chevron-down.svg',
    subscription: 'advance',
    royaltyFree: 'Public Domain'
  }
]

export const emptyUser = {
  plan: '',
  name: ''
}

export type I18NEXT = {
  [key: string]: I18NEXT | string
}

export const plans = [
  {
    name: 'basic',
    wordsNumber: 15,
  },
  {
    name: 'advance',
    wordsNumber: 50,
  },
  {
    name: 'pro',
    wordsNumber: 100,
  }
]

export const i18next: I18NEXT = {
  header: {
    plan: {
      basic: 'BASIC PLAN 2/15'
    }
  }
}